export function isArray(obj: Object): boolean;
export function isBoolean(obj: Object): boolean;
export function isDate(obj: Object): boolean;
export function isNumber(obj: Object): boolean;
export function isObject(obj: Object): boolean;
export function isRegExp(obj: Object): boolean;
export function isString(obj: Object): boolean;
export function nanoTime(): string;
export function each(iterable: Object, callback: (object: Object, index?: number) => void): void;
export function extend(receiver: Object, contributor: Object): Object;
