export function isArray(obj: any): boolean;
export function isBoolean(obj: any): boolean;
export function isDate(obj: any): boolean;
export function isNumber(obj: any): boolean;
export function isObject(obj: any): boolean;
export function isRegExp(obj: any): boolean;
export function isString(obj: any): boolean;
export function nanoTime(): string;
export function each(iterable: any, callback: (object: any, index?: number) => void): void;
export function extend(receiver: any, contributor: any): any;
